salutation.message.element = //*[contains(text(),"Products")]
backpack.product.button.element = add-to-cart-sauce-labs-backpack
tshirt.product.button.element = add-to-cart-sauce-labs-bolt-t-shirt
redtshirt.product.button.element = add-to-cart-sauce-labs-fleece-jacket
addtocart.button.element = shopping_cart_link

